# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  schedule:
    - cron:  '30 1 * * *'  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: build libs
      #run: |
        # export QT_CI_LOGIN=${{secrets.QT_CI_LOGIN}}
        # export QT_CI_PASSWORD=${{secrets.QT_CI_PASSWORD}}
        # make all_qt
      run: |
        make dependencies
        make libparc_src
        make hicn_src
        make hicn_package
        mv build/hicn/hicn-*.pkg build/hicn/hicn.pkg
    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_number }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false
    - name: Upload Release Asset (hicn.pkg)
      if: github.ref == 'refs/heads/master'
      id: upload-release-asset-hicn-pkg 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/hicn/hicn.pkg
        asset_name: hicn-Darwin.pkg
        asset_content_type: application/zip
    - uses: dev-drprasad/delete-older-releases@v0.1.0
      if: github.ref == 'refs/heads/master'
      id: delete-older-releases
      with:
        repo: icn-team/macos-sdk
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
